services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 25883:80
    env_file:
      - .env
    depends_on:
      - database
    user: "${UID}:${GID}"
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/