services:
  website:
    build:
      context: ./website
      dockerfile: dev.Dockerfile
    ports:
      - 25880:3000
    volumes:
      - ./website:/app
    command: npm run watch
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
     - 25881:8080
  database:
    image: "postgres:latest"
    ports:
      - 25882:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: panic_spiral
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
