services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run start
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
     - "3001:80"
    
