services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - 25880:3000
    environment:
      - NODE_ENV=production
    command: npm run start
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
     - 25881:80
  database:
    image: "postgres:latest"
    ports:
      - 25882:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: panic_spiral
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 25883:80
    env_file:
      - .env
    depends_on:
      - database
    user: "${UID}:${GID}"
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/