import { sprintf } from "sprintf-js";
import { KEY_BINDINGS } from "../../keyBindings";
import { i18n, i18nKeys } from "../../Utils";
import { GRID_OFFSET } from "./Ship";

export const SYSTEM_IDS = {
  ENGINE: "Engine",
  MEDBAY: "Medbay",
  OXYGEN: "O2",
  REACTOR: "Reactor",
  SHIELDS: "Shields",
};

export const SYSTEM_TRANSLATION_KEYS = {
  [SYSTEM_IDS.ENGINE]: i18nKeys.ENGINE,
  [SYSTEM_IDS.MEDBAY]: i18nKeys.MEDBAY,
  [SYSTEM_IDS.OXYGEN]: i18nKeys.OXYGEN,
  [SYSTEM_IDS.REACTOR]: i18nKeys.REACTOR,
  [SYSTEM_IDS.SHIELDS]: i18nKeys.SHIELDS,
};

export const SYSTEM_BREAKDOWN_CHECK_START = 5000;
export const SYSTEM_BREAKDOWN_CHECK_INTERVAL = 1000;
export const SYSTEM_BREAKDOWN_CHECK_COOLDOWN = 2000;

export const SYSTEM_BREAKDOWN_RATE = {
  [SYSTEM_IDS.ENGINE]: 0.07,
  [SYSTEM_IDS.MEDBAY]: 0.05,
  [SYSTEM_IDS.OXYGEN]: 0.05,
  [SYSTEM_IDS.REACTOR]: 0.05,
  [SYSTEM_IDS.SHIELDS]: 0.05,
};

export const SYSTEM_REPAIR_COOLDOWNS = {
  [SYSTEM_IDS.ENGINE]: 5000,
  [SYSTEM_IDS.MEDBAY]: 5000,
  [SYSTEM_IDS.OXYGEN]: 5000,
  [SYSTEM_IDS.REACTOR]: 5000,
  [SYSTEM_IDS.SHIELDS]: 5000,
};

export const SYSTEM_REPAIR_SCORE = {
  [SYSTEM_IDS.ENGINE]: 20,
  [SYSTEM_IDS.MEDBAY]: 20,
  [SYSTEM_IDS.OXYGEN]: 20,
  [SYSTEM_IDS.REACTOR]: 20,
  [SYSTEM_IDS.SHIELDS]: 20,
};

export const DEFAULT_INTERACTION_TEXT = sprintf(
  i18n(i18nKeys.REPAIR_INSTRUCTIONS),
  KEY_BINDINGS.PLAYER_CONTROLS.INTERACT
);

export const SYSTEM_TOOLTIP_OFFSET = {
  X: -GRID_OFFSET.X / 2,
  Y: -GRID_OFFSET.Y / 2,
  Y_MODIFIER: -50,
};
