export const SYSTEM_MONITOR_DEFAULTS = {
  MONITOR_PADDING: 10,
  STATUS_FONT_SIZE: 18,
  STATUS_SPACING: 10,
  STATUS_PADDING: 5,
  STATUS_FONT_STROKE: "#000000",
  STATUS_POLYGON_WIDTH: 200,
  STATUS_FINE_BACKGROUND_FILL: "#44AD4D",
  STATUS_BROKEN_BACKGROUND_FILL: "#791308",
  STATUS_BACKGROUND_STROKE: "#FFFFFF",
  STATUS_POLYGON_INDENT: 10,
};
