export const GAME_SIZE = {
  WIDTH: 1280,
  HEIGHT: 800,
};

export const SYSTEM_MONITOR_DEFAULTS = {
  MONITOR_PADDING: 10,
  STATUS_FONT_SIZE: 18,
  STATUS_SPACING: 10,
  STATUS_PADDING: 5,
  STATUS_FONT_STROKE: "#000000",
  STATUS_POLYGON_WIDTH: 200,
  STATUS_FINE_BACKGROUND_FILL: "#44AD4D",
  STATUS_BROKEN_BACKGROUND_FILL: "#791308",
  STATUS_BACKGROUND_STROKE: "#FFFFFF",
  STATUS_POLYGON_INDENT: 10,
};

export const SCORE_DEFAULTS = {
  SCORE_SPACING: 10,
  SCORE_PADDING: 5,
  HEADER_FONT_SIZE: 18,
  SCORE_FONT_SIZE: 24,
  SCORE_INCREMENT_STOPPED_FONT_COLOUR: "#BD352A",
  SCORE_INCREMENTING_FONT_COLOUR: "#FFFFFF",
};

export const ROUND_DEFAULTS = {
  HEADER_FONT_SIZE: 18,
  REMAINING_TIME_FONT_SIZE: 32,
  ROUND_SPACING: 10,
  ROUND_PADDING: 5,
};

const ROUND_END_PADDING = {
  X: 200,
  Y: 20,
};

export const ROUND_END = {
  EXTERNAL_PADDING: {
    X: ROUND_END_PADDING.X,
    Y: ROUND_END_PADDING.Y,
  },
  OVERLAY_WIDTH: GAME_SIZE.WIDTH - 2 * ROUND_END_PADDING.X,
  OVERLAY_HEIGHT: GAME_SIZE.HEIGHT - 2 * ROUND_END_PADDING.Y,
  OVERLAY_CORNER_RADIUS: 5,
  OVERLAY_FILL: "#000000EE",
  OVERLAY_STROKE_COLOUR: "#FFFFFF",
  OVERLAY_STROKE_WIDTH: 3,
  HEADER_PADDING: {
    TOP: 50,
    BOTTOM: 50,
  },
  HEADER_FONT_SIZE: 40,
  NEXT_ROUND_BUTTON_PADDING: {
    BOTTOM: 20,
  },
  STATS_PADDING: {
    LEFT: 100,
  },
};
