import { sprintf } from "sprintf-js";
import { KEY_BINDINGS } from "../../keyBindings";
import { i18n, i18nKeys } from "../../Utils";
import { GRID_OFFSET } from "./Ship";

export const SYSTEM_IDS = {
  ENGINE: "Engine",
  MEDBAY: "Medbay",
  OXYGEN: "O2",
  REACTOR: "Reactor",
  ENGINEERING: "Engineering",
  PILOTING: "Piloting",
};

export const SYSTEM_TRANSLATION_KEYS = {
  [SYSTEM_IDS.ENGINE]: i18nKeys.ENGINE,
  [SYSTEM_IDS.MEDBAY]: i18nKeys.MEDBAY,
  [SYSTEM_IDS.OXYGEN]: i18nKeys.OXYGEN,
  [SYSTEM_IDS.REACTOR]: i18nKeys.REACTOR,
  [SYSTEM_IDS.ENGINEERING]: i18nKeys.ENGINEERING,
};

export const SYSTEM_BREAKDOWN_CHECK_START = 5000;
export const SYSTEM_BREAKDOWN_CHECK_INTERVAL = 1000;
export const SYSTEM_BREAKDOWN_CHECK_COOLDOWN = 2000;

export const SYSTEM_BREAKDOWN_RATE = {
  [SYSTEM_IDS.ENGINE]: 0.05,
  [SYSTEM_IDS.MEDBAY]: 0.1,
  [SYSTEM_IDS.OXYGEN]: 0.07,
  [SYSTEM_IDS.REACTOR]: 0.07,
  [SYSTEM_IDS.ENGINEERING]: 0.1,
};

export const SYSTEM_REPAIR_COOLDOWNS = {
  [SYSTEM_IDS.ENGINE]: 5000,
  [SYSTEM_IDS.MEDBAY]: 5000,
  [SYSTEM_IDS.OXYGEN]: 5000,
  [SYSTEM_IDS.REACTOR]: 5000,
  [SYSTEM_IDS.ENGINEERING]: 5000,
};

export const SYSTEM_REPAIR_SCORE = {
  [SYSTEM_IDS.ENGINE]: 20,
  [SYSTEM_IDS.MEDBAY]: 20,
  [SYSTEM_IDS.OXYGEN]: 20,
  [SYSTEM_IDS.REACTOR]: 20,
  [SYSTEM_IDS.ENGINEERING]: 20,
};

export const REACTOR_HEALTH_DAMAGE_INTERVAL = 3000;
export const REACTOR_HEALTH_DAMAGE = 1;

export const OXYGEN_HEALTH_DAMAGE_INTERVAL = 3000;
export const OXYGEN_HEALTH_DAMAGE = 1;

export const ROUND_END_SAFE_TIME = 5;

export const BREAKDOWN_RATE_SCALING = 0.01;

export const DEFAULT_INTERACTION_TEXT = sprintf(
  i18n(i18nKeys.REPAIR_INSTRUCTIONS),
  KEY_BINDINGS.PLAYER_CONTROLS.INTERACT
);

export const PILOTING_TERMINAL_ACTIVE_DURATION: { [key: string]: number } = {
  TERMINAL_1: 5000,
  TERMINAL_2: 8000,
  TERMINAL_3: 15000,
};

export const DEFAULT_PILOTING_TEXT = sprintf(
  i18n(i18nKeys.PILOTING_INSTRUCTIONS),
  KEY_BINDINGS.PLAYER_CONTROLS.INTERACT
);

export const SYSTEM_TOOLTIP_OFFSET = {
  X: -GRID_OFFSET.X / 2,
  Y: -GRID_OFFSET.Y / 2,
  Y_MODIFIER: -50,
};
