import { COMMON } from "..";

export const SYSTEM_MONITOR_DEFAULTS = {
  MONITOR_PADDING: 10,
  STATUS_FONT_SIZE: 18,
  STATUS_SPACING: 10,
  STATUS_PADDING: 5,
  STATUS_FONT_STROKE: "#000000",
  STATUS_POLYGON_WIDTH: 200,
  STATUS_FINE_BACKGROUND_FILL: "#44AD4D",
  STATUS_BROKEN_BACKGROUND_FILL: "#791308",
  STATUS_BACKGROUND_STROKE: "#FFFFFF",
  STATUS_POLYGON_INDENT: 10,
};

export const SCORE = {
  SCORE_SPACING: 10,
  SCORE_PADDING: 5,
  HEADER_FONT_SIZE: 18,
  SCORE_FONT_SIZE: 24,
  SCORE_INCREMENT_STOPPED_FONT_COLOUR: "#BD352A",
  SCORE_INCREMENTING_FONT_COLOUR: "#FFFFFF",
};

export const SCORE_MULTIPLIER = {
  LIGHTS_MARGIN: {
    X: 10,
    Y: 8,
  },
  LIGHTS: {
    COLOUR: "#00FFFF",
    WIDTH: 5,
    SPACING: 5,
  },
};

export const ROUND_DEFAULTS = {
  HEADER_FONT_SIZE: 18,
  REMAINING_TIME_FONT_SIZE: 32,
  ROUND_SPACING: 10,
  ROUND_PADDING: 5,
};

const ROUND_END_PADDING = {
  X: 200,
  Y: 20,
};

export const ROUND_END = {
  EXTERNAL_PADDING: {
    X: ROUND_END_PADDING.X,
    Y: ROUND_END_PADDING.Y,
  },
  OVERLAY_WIDTH: COMMON.UI.GAME_SIZE.WIDTH - 2 * ROUND_END_PADDING.X,
  OVERLAY_HEIGHT: COMMON.UI.GAME_SIZE.HEIGHT - 2 * ROUND_END_PADDING.Y,
  OVERLAY_CORNER_RADIUS: 5,
  OVERLAY_FILL: "#000000EE",
  OVERLAY_STROKE_COLOUR: "#FFFFFF",
  OVERLAY_STROKE_WIDTH: 3,
  HEADER_PADDING: {
    TOP: 50,
    BOTTOM: 100,
  },
  HEADER_FONT_SIZE: 40,
  SCORE_HEADER_FONT_SIZE: 32,
  SCORE_BREAKDOWN_FONT_SIZE: 24,
  TOTAL_SCORE_FONT_SIZE: 28,
  SCORE_BREAKDOWN_PADDING: {
    BOTTOM: 10,
    RIGHT: 80,
  },
  NEXT_ROUND_BUTTON_PADDING: {
    BOTTOM: 20,
  },
  STATS_HEADER_FONT_SIZE: 24,
  STATS_HEADER_PADDING: {
    BOTTOM: 10,
  },
  STATS_ITEM_FONT_SIZE: 18,
  STATS_ITEM_PADDING: {
    BOTTOM: 10,
    RIGHT: 80,
  },
  STATS_CONTAINER_PADDING: {
    TOP: 30,
    LEFT: 100,
    RIGHT: 100,
  },
};

export const SHIP_HEALTH_BAR = {
  HEIGHT: 30,
  WIDTH: 300,
  CORNER_RADIUS: 3,
  BACKGROUND_FILL: "#000000EE",
  STROKE_COLOUR: "#FFFFFF",
  STROKE_WIDTH: 2,
  BASE_FILL: "#FFFFFF",
  MARGIN: {
    TOP: 10,
    LEFT: 10,
  },
  PADDING: {
    TOP: 5,
    BOTTOM: 5,
  },
  LABEL_STROKE: {
    COLOUR: "#000000",
    WIDTH: 2,
  },
  LABEL_PADDING: {
    LEFT: 10,
    TOP: 3,
    BOTTOM: 5,
    RIGHT: 5,
  },
  BLOCK_PADDING: 3,
  TINT: {
    HEALTHY: "#44AD4D",
    WARNING: "#FFDD00",
    DANGER: "#FF0000",
  },
  THRESHOLDS: {
    WARNING: 0.66,
    DANGER: 0.33,
  },
};

export const PLAYER_HEALTH_BAR = {
  HEIGHT: 5,
  WIDTH: 24,
  BACKGROUND_FILL_COLOUR: "#000000",
  BASE_FILL: "#FFFFFF",
  TINT: {
    HEALTHY: "#00FF00",
    WARNING: "#FFDD00",
    DANGER: "#FF0000",
  },
  DAMAGE_TAKEN_FILL_COLOR: "#ffffff",
  DAMAGE_TAKEN_VISIBLE_MS: 250,
  POSITION: {
    X: -12,
    Y: -24,
  },
  THRESHOLDS: {
    WARNING: 0.66,
    DANGER: 0.33,
  },
};

export const PILOTING_TERMINAL = {
  COOLDOWN_BAR_OFFSET: 2,
  COOLDOWN_BAR_STARTING_WIDTH: 30,
  COOLDOWN_BAR_COLOUR: "#00FFFF",
};

export const SHIP = {
  TEXT: {
    FILL: "#FFFFFFDD",
    STROKE: "#000000DD",
  },
};
