export const TOOLTIP_DEFAULTS = {
  FONT_SIZE: 14,
  STROKE: "#000000",
  WORD_WRAP_WIDTH: 250,
  PADDING: 10,
  BACKGROUND_FILL: "#00000055",
  BORDER_STROKE: "#ffffff99",
  BACKGROUND_CORNER_RADIUS: 5,
};

export const SYSTEM_MONITOR_DEFAULTS = {
  MONITOR_PADDING: 10,
  STATUS_FONT_SIZE: 18,
  STATUS_SPACING: 10,
  STATUS_PADDING: 5,
  STATUS_FONT_STROKE: "#000000",
  STATUS_POLYGON_WIDTH: 200,
  STATUS_FINE_BACKGROUND_FILL: "#44AD4D",
  STATUS_BROKEN_BACKGROUND_FILL: "#791308",
  STATUS_BACKGROUND_STROKE: "#FFFFFF",
  STATUS_POLYGON_INDENT: 10,
};
